version: "2"

linters:
  default: none
  enable:
    - caseorder
  settings:
    custom:
      caseorder:
        type: "module"
        description: Enforces ordering of switch blocks
        path: caseorder
